name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Lint (flake8)
        run: flake8

      - name: Run tests with coverage (pytest)
        run: pytest -q --maxfail=1 --disable-warnings --cov=app --cov-report=xml

  sast-sonar:
    runs-on: ubuntu-latest
    needs: build-test-lint
    if: ${{ secrets.SONAR_TOKEN != '' }}
    steps:
      - name: Checkout (full history for blame/branches)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.qualitygate.wait=true

  secrets-scan:
    runs-on: ubuntu-latest
    needs: build-test-lint
    steps:
      - name: Checkout (full history for scanning)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog Secret Scan
        uses: trufflesecurity/trufflehog-actions-scan@v0.20.4
        with:
          scanArguments: --only-verified
