target-version = "py311"
line-length = 100

[lint]
select = ["E","F","I","UP","B"]
ignore = ["E501"]

[lint.isort]
force-sort-within-sections = true
known-first-party = ["secure-sms", "secure_sms"]
profile = "black"
