name: Bandit

# Security scanning workflow using Bandit.  This job runs on pushes,
# pull requests and on a weekly schedule.  It executes the Bandit
# security scanner against the Python code in the secure-sms directory.
# The exit code is forced to zero so that findings do not fail the
# pipeline; instead, address issues as you see fit.

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  schedule:
    # run at 07:00 every Monday
    - cron: '0 7 * * 1'

permissions:
  contents: read

jobs:
  bandit-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit security scan
        run: |
          # Scan the application directory recursively.  --exit-zero
          # prevents the command from failing the job on findings.
          bandit -r secure-sms -ll --exit-zero