name: Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read

env:
  PROJECT_DIR: secure_SMS

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.PROJECT_DIR }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sanity check paths
        run: |
          set -euxo pipefail
          pwd
          ls -la
          echo "PROJECT_DIR=${PROJECT_DIR}"
          test -d "${PROJECT_DIR}"
          ls -la "${PROJECT_DIR}" | head -n 50

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install & test (coverage)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov
          pytest -q --disable-warnings --maxfail=1 \
            --cov=. --cov-report=xml --cov-report=term

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  # uncomment for self-hosted
