name: Build

    on:
      push:
        branches: [ "main", "master" ]
      pull_request:
        types: [opened, synchronize, reopened]

    permissions:
      contents: read
      pull-requests: read

    env:
      PROJECT_DIR: secure-sms
      # Ensure the project directory is added to PYTHONPATH so top-level modules like
      # run.py can be imported during the build and test steps.  Without this,
      # pytest may fail with ModuleNotFoundError because the working directory
      # contains a hyphen and isn't added to sys.path by default.
      PYTHONPATH: ${{ github.workspace }}/${{ env.PROJECT_DIR }}

    jobs:
      build-and-scan:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ${{ env.PROJECT_DIR }}
        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
              fetch-depth: 0

          - name: Sanity check paths
            run: |
              set -euxo pipefail
              pwd
              ls -la
              echo "PROJECT_DIR=${PROJECT_DIR}"
              test -d "${PROJECT_DIR}"
              ls -la "${PROJECT_DIR}" | head -n 50

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: "3.11"
              cache: pip

          - name: Install & test (coverage)
            run: |
              python -m pip install --upgrade pip
              if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
              pip install pytest pytest-cov
              pytest -q --disable-warnings --maxfail=1 --cov=. --cov-report=xml --cov-report=term

          - name: SonarQube Scan
            uses: SonarSource/sonarqube-scan-action@v6
            env:
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              # SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  # uncomment if self-hosted