name: Package App (artifact)

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create source tarball
        run: |
          tar -czf source.tar.gz .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: source-package
          path: source.tar.gz
