name: Pylint

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    defaults:
      run:
        working-directory: secure-sms
    steps:
<<<<<<< Updated upstream
      - name: Checkout
=======
      - name: Checkout source
>>>>>>> Stashed changes
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

<<<<<<< Updated upstream
      - name: Install deps
=======
      - name: Install dependencies and Pylint
>>>>>>> Stashed changes
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run pylint
<<<<<<< Updated upstream
        run: |
          pylint $(git ls-files '*.py' | tr '\n' ' ')
=======
        # Run Pylint on all tracked Python files.  Use --exit-zero so that
        # Pylint warnings and informational messages do not cause the workflow
        # to fail.  This allows the lint job to surface issues without blocking
        # other checks.
        run: |
          pylint --exit-zero $(git ls-files '*.py' | tr '\n' ' ')
>>>>>>> Stashed changes
