name: Lint (Pylint)

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pylint

      - name: Run Pylint
        run: |
          # Lint all tracked Python files; adjust rcfile if you have one.
          pylint $(git ls-files '*.py')
